# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # Add permissions for gh-pages to push to the master branch
    permissions:
      contents: write

    strategy:
      matrix:
        # Test on multiple node versions as requested
        node-version: [18.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test

    - name: Copy README.md to public
      run: cp README.md public

    - name: Update script.js for deployment
      run: sed -i "s|'../README.md'|'README.md'|g" public/script.js

    - name: Generate OGP Image from GAS JSON
      run: |
        # 1. GASã‹ã‚‰JSONã‚’å–å¾—
        # â€» URLã®æœ«å°¾ã«ã‚¿ã‚¤ãƒˆãƒ«ã‚’æ¸¡ã™
        JSON_RESPONSE=$(curl -L -s "https://script.google.com/macros/s/AKfycbzbMAKxkzHlwN8SY7ygJA34xYESMNNdkGNt8vv1XMcZSksgHsUwOxCCdP-wgg6fv7M/exec?t=Fumikazu%20%E2%80%9CFreddie%E2%80%9D%20Fujiwara%27s%20Portfolio")

        # 2. jqã‚³ãƒãƒ³ãƒ‰ã§JSONã‹ã‚‰"png"ã‚­ãƒ¼ã®å€¤ã ã‘ã‚’æŠœãå‡ºã—ã€base64ã§ãƒ‡ã‚³ãƒ¼ãƒ‰ã—ã¦ä¿å­˜
        echo $JSON_RESPONSE | jq -r '.png' | base64 -d > ./public/ogp.png

        # 3. ç¢ºèªï¼ˆãƒ•ã‚¡ã‚¤ãƒ«ãŒç”Ÿæˆã•ã‚ŒãŸã‹ã€ã‚µã‚¤ã‚ºã¯æ­£å¸¸ã‹ã‚’è¡¨ç¤ºï¼‰
        ls -lh ./public/ogp.png

    - name: "Deploy to gh-pages ğŸš€"
      uses: JamesIves/github-pages-deploy-action@releases/v3
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.node-version == '22.x'
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public
